# config/settings.yaml
spark:
  app_name: "dataeng_pyspark_data_pipeline_29abd"

paths:
  pedidos: "data/input/pedidos"
  pagamentos: "data/input/pagamentos"
  output: "data/output/relatorio"

file_options:
  pedidos_csv:
    compression: "gzip"
    header: True
    sep: ";"
    